#!/bin/bash

CONFIG=$(dirname $0)/config.app
if [ ! -f ${CONFIG} ]; then
    echo $(basename $0): Adapt FILE:config.dist and save it as $(basename ${CONFIG}) 
    exit 1
else
    . ${CONFIG}
fi

###
# tiny things for convenience
#

waitforapp() {
    until [[ ${line} == "APP: READY" ]]
    do
        read -t ${KW_TMOUT} line < ${FIFO}

        if [[ $? != 0 ]]
        then
            eval ${KILLALL} && sleep 1
            rm -rf "${APPPROFILEDIR}"
            rm -f "${FIFO}"
            return 10
        elif [[ ${line:0:8} == "RES: ERR" ]]
        then
            echo "${line}"
            return 20
        elif [[ ${line:0:9} == "APP: STOP" ]]
        then
            echo "${line}"
            return 30
        fi

        echo "${line}"
    done
    line=""
}

chkfifo() {
    if [[ ! -p $FIFO ]]; then
        mkfifo -m 0600 $FIFO || return 1
        echo "$(basename $0): created FIFO ${FIFO}"
    fi
}
#
#
###

if [ ${GRID:+1} ]
then
    FIFO=${TMPDIR:-"/tmp"}/krdwrd-${GR_DISPLAY}.fifo
    APPPROFILEDIR="${TMPDIR:-"/tmp"}/.krdwrd.org.${GRID}"
    KILLALL="pkill -9 -f 'xulrunner-bin.*-KWID${GRID}.ini'"

    APPINI=${APP}/application-${GRID}.ini
    export APPINI
    if [[ ! -e $APPINI ]]
    then
        sed -e "s#^ID\(.*\)#ID\1\nProfile=krdwrd.org.${GRID}#" ${APP}/application.ini \
            > ${APPINI}
        echo "$(basename $0): created file $APPINI"
    fi
    export KW_DISPLAY=${GR_DISPLAY}
else
    FIFO=${APP}/krdwrd.fifo
    APPPROFILEDIR="${HOME}/.krdwrd.org/krdwrd"
    KILLALL="pkill -9 -f 'xulrunner-bin.*-KWID.ini'"
fi

chkfifo || exit 1
mkdir -p ${APPPROFILEDIR} || exit 1
$(dirname $0)/krdwrd -profile "${APPPROFILEDIR}" -follow -KWID${GRID}.ini -tmout 10000 $@ 1>$FIFO 2>&2 &
waitforapp
