#!/bin/bash

CONFIG=$(dirname $0)/config.app
if [ ! -f ${CONFIG} ]; then
    echo $(basename $0): Adapt FILE:config.dist and save it as $(basename ${CONFIG}) 
    exit 1
else
    . ${CONFIG}
fi

###
# tiny things for convenience
#

waitforapp() {
    until [[ ${line} == "APP: READY" ]]
    do
        read -t ${KW_TMOUT} line < ${FIFO}

        if [[ $? != 0 ]]
        then
            eval ${KILLALL} && sleep 1
            rm -f "${HOME}/.krdwrd.org/profiles.ini"
            rm -rf "${HOME}"/.krdwrd.org/*.default/
            return 10
        elif [[ ${line:0:8} == "RES: ERR" ]]
        then
            echo "${line}"
            return 20
        elif [[ ${line:0:9} == "APP: STOP" ]]
        then
            echo "${line}"
            return 30
        fi

        echo "${line}"
    done
    line=""
}

chkfifo() {
    if [[ ! -p $FIFO ]]; then
        mkfifo -m 0600 $FIFO || return 1
        echo "$(basename $0): created FIFO ${FIFO}"
    fi
}
#
#
###

#KW_TMOUT=8
FIFO=${APP}/krdwrd.fifo
chkfifo || exit 1

$(dirname $0)/krdwrd -follow -tmout 10000 $@ 1>$FIFO 2>&2 &

KILLALL="pkill -9 -f 'xulrunner-bin.*krdwrd'"
waitforapp
