#!/bin/bash

CONFIG=$(dirname $0)/config.app
if [ ! -f ${CONFIG} ]; then
    echo $(basename $0): Adapt FILE:config.dist and save it as $(basename ${CONFIG}) 
    exit 1
else
    . ${CONFIG}
fi

KW_TMOUT=10

###
# tiny things for convenience
#

waitforapp() {
    until [[ ${line} == "APP: READY" ]]
    do
        read -t ${KW_TMOUT} line < ${FIFO}

        if [[ $? != 0 ]]
        then
            eval ${KILLALL} && sleep 1
            return 1
        elif [[ ${line:0:8} == "RES: ERR" ]]
        then
            echo ${line}
            return 1
        fi

        echo ${line}
    done
    line=""
}

chkfifo() {
    if [[ ! -p $FIFO ]]; then
        echo "$(basename $0): created FIFO ${FIFO}"
        mkfifo $FIFO
    fi
}
#
#
###

[ -z ${GRID} ] \
    && (echo "$(basename $0): missing value for GRID"; exit 10)
[ -z ${GR_DISPLAY} ] \
    && (echo "$(basename $0): missing value for GR_DISPLAY"; exit 10)

if [[ ! -e $APP/application-${GRID}.ini ]]
then
    echo "$(basename $0): creating file $APP/application-${GRID}.ini"
    sed -e "s#^ID\(.*\)#ID\1\nProfile=krdwrd.org.${GRID}#" ${APP}/application.ini \
        > ${APP}/application-${GRID}.ini
fi

FIFO=${APP}/krdwrd-${GRID}.fifo
chkfifo

# $(dirname $0)/krdwrd -follow $@ 1>$FIFO 2>&2 &
DISPLAY=:${GR_DISPLAY}.${KW_SCREEN} ${XULRUNNER} \
    $APP/application-${GRID}.ini -follow $@ 1>$FIFO 2>&2 &

KILLALL="pkill -f 'xulrunner-bin.*krdwrd.*-${GRID}'"
waitforapp
