#!/bin/bash

CONFIG=$(dirname $0)/config.app
if [ ! -f ${CONFIG} ]; then
    echo $(basename $0): Adapt FILE:config.dist and save it as $(basename ${CONFIG}) 
    exit 1
else
    . ${CONFIG}
fi

###
# tiny things for convenience
#

waitforapp() {
    until [[ ${line} == "APP: READY" ]]
    do
        read -t ${KW_TMOUT} line < ${FIFO}

        if [[ $? != 0 ]]
        then
            eval ${KILLALL} && sleep 1
            rm -f "${HOME}/.krdwrd.org.${GRID}/profiles.ini"
            rm -rf "${HOME}"/.krdwrd.org."${GRID}"/*.default/
            return 10
        elif [[ ${line:0:8} == "RES: ERR" ]]
        then
            echo "${line}"
            return 20
        elif [[ ${line:0:9} == "APP: STOP" ]]
        then
            echo "${line}"
            return 30
        fi

        echo "${line}"
    done
    line=""
}

chkfifo() {
    if [[ ! -p $FIFO ]]; then
        mkfifo -m 0600 $FIFO || return 1
        echo "$(basename $0): created FIFO ${FIFO}"
    fi
}
#
#
###

[ -z ${GRID} ] \
    && (echo "$(basename $0): missing value for GRID"; exit 10)
[ -z ${GR_DISPLAY} ] \
    && (echo "$(basename $0): missing value for GR_DISPLAY"; exit 10)

if [[ ! -e $APP/application-${GRID}.ini ]]
then
    echo "$(basename $0): creating file $APP/application-${GRID}.ini"
    sed -e "s#^ID\(.*\)#ID\1\nProfile=krdwrd.org.${GRID}#" ${APP}/application.ini \
        > ${APP}/application-${GRID}.ini
fi

KW_TMOUT=8
FIFO=/tmp/krdwrd-${GR_DISPLAY}.fifo
chkfifo || exit 1

# $(dirname $0)/krdwrd -follow $@ 1>$FIFO 2>&2 &
DISPLAY=:${GR_DISPLAY}.${KW_SCREEN} ${XULRUNNER} \
    $APP/application-${GRID}.ini -KWID${GRID}.ini -tmout 4000 $@ 1>$FIFO 2>&2 &

KILLALL="pkill -9 -f 'xulrunner-bin.*-KWID${GRID}.ini'"
waitforapp
